### ISSUE TITLE
导出rknn模型出现错误

### ISSUE THREAD

**Issue by EthanWsir** [rockchip-linux/rknpu2#113]
请问一下大佬，我在运行examples/rknn_yolov5_demo/convert_rknn_demo/yolov5/onnx2rknn.py这个文件，到Building model那一步就开始报错了，报错提示为下面的内容，请问我要如何处理这个报错。
E Catch exception when building RKNN model!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 624, in rknn.api.rknn_base.RKNNBase.build
E   File "rknn/api/rknn_base.py", line 1511, in rknn.api.rknn_base.RKNNBase._quantize2
E FileNotFoundError: [Errno 2] No such file or directory: './dataset.txt'
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

**Comment by CaA23187** [comment]
路径的问题, 提示是找不到dataset.txt这个文件. 你cd到有dataset.txt这个文件下面的路径运行就好了
