### ISSUE TITLE
Matmul example segfault on aarch64 Linux RK3588 

### ISSUE THREAD

**Issue by marty1885** [rockchip-linux/rknpu2#88]
Hi, I am interested in using the low level API of RKNPU2. I tried to run the matmul example but it crashed with the following output if I enable address sanitizer:

I'm using the latest commit of RKNPU2

```❯ make && ./rknn_matmul_demo
Consolidate compiler generated dependencies of target rknn_matmul_demo
[ 50%] Building CXX object CMakeFiles/rknn_matmul_demo.dir/src/rknn_matmul_demo.cpp.o
[100%] Linking CXX executable rknn_matmul_demo
[100%] Built target rknn_matmul_demo
MatMul M=4, K=64, N=32
input/output matmul tensor attribute:
  name=A, dims=(4, 64), size=256, type=INT8
  name=B, dims=(64, 32), size=2048, type=INT8
  name=C, dims=(4, 32), size=512, type=INT32
Begin perf ...
AddressSanitizer:DEADLYSIGNAL
=================================================================
==15525==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000006c (pc 0xffffbc87e308 bp 0xffffe2f1cd20 sp 0xffffe2f1cd00 T0)
==15525==The signal is caused by a WRITE memory access.
==15525==Hint: address points to the zero page.
    #0 0xffffbc87e308  (/home/marty/Documents/not-my-projects/rknpu2/examples/rknn_matmul_api_demo/../../runtime/RK3588/Linux/librknn_api/aarch64/librknnrt.so+0x20e308)
    #1 0xaaaab9e6448c in main /home/marty/Documents/not-my-projects/rknpu2/examples/rknn_matmul_api_demo/src/rknn_matmul_demo.cpp:246
    #2 0xffffbc1e73f8  (/lib/aarch64-linux-gnu/libc.so.6+0x273f8)
    #3 0xffffbc1e74c8 in __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x274c8)
    #4 0xaaaab9e61bac in _start (/home/marty/Documents/not-my-projects/rknpu2/examples/rknn_matmul_api_demo/build/build_linux_aarch64/rknn_matmul_demo+0x1bac)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/marty/Documents/not-my-projects/rknpu2/examples/rknn_matmul_api_demo/../../runtime/RK3588/Linux/librknn_api/aarch64/librknnrt.so+0x20e308) 
==15525==ABORTING
```

**Comment by marty1885** [comment]
Small update: I made an even smaller example that reproduces the same issue.
```c
int main(int argc, char* argv[])
{
  rknn_matmul_info info;
  info.M = 1;
  info.K = 32; // This must be a multipe of 32 on 3588
  info.N = 32;

  info.type          = RKNN_TENSOR_INT8;
  info.native_layout = 0;
  info.perf_layout   = 0;

  rknn_matmul_ctx ctx;

  rknn_matmul_io_attr io_attr;
  memset(&io_attr, 0, sizeof(rknn_matmul_io_attr));

  int ret = rknn_matmul_create(&ctx, &info, &io_attr);
  if (ret < 0) {
    printf("rknn_matmul_create fail! ret=%d\n", ret);
    return -1;
  }
  rknn_tensor_mem* A = rknn_create_mem(ctx, io_attr.A.size);
  rknn_tensor_mem* B = rknn_create_mem(ctx, io_attr.B.size);
  rknn_tensor_mem* C = rknn_create_mem(ctx, io_attr.C.size);

  memset(B->virt_addr, 1, B->size);
  memset(A->virt_addr, 1, B->size);


  ret = rknn_matmul_set_io_mem(ctx, A, &io_attr.A);
  if (ret < 0) {
    printf("rknn_matmul_set_io_mem fail! ret=%d\n", ret);
    return -1;
  }

  ret = rknn_matmul_set_io_mem(ctx, B, &io_attr.B);
  if (ret < 0) {
    printf("rknn_matmul_set_io_mem fail! ret=%d\n", ret);
    return -1;
  }

  ret = rknn_matmul_set_io_mem(ctx, C, &io_attr.C);
  if (ret < 0) {
    printf("rknn_matmul_set_io_mem fail! ret=%d\n", ret);
    return -1;
  }

  ret = rknn_matmul_run(ctx);
  if (ret < 0) {
    printf("rknn_matmul_run error %d\n", ret);
    return -1;
  }

  rknn_destroy_mem(ctx, A);
  rknn_destroy_mem(ctx, B);
  rknn_destroy_mem(ctx, C);

  rknn_matmul_destroy(ctx);
```

**Comment by ponzienjoyer** [comment]
Wanted to add a +1 to this issue here - trying to see if I can't use the NPU as a backend for [llama.cpp](https://github.com/ggerganov/llama.cpp) and hitting segfaults trying to run the example in the repository.

**Comment by marty1885** [comment]
@ponzienjoyer Me too. I was trying to port llama.cpp and rwkv.cpp to NPU. But failed at this step.

**Comment by marty1885** [comment]
Quick update. I wrote a RKNPU2 backend for llama.cpp. Unfortunately it is not faster then just using the CPU and generates questionable output (unstable sentences when too many layers run on the NPU). Not sure what to do with it. But feel free to have a look.

https://github.com/marty1885/llama.cpp/tree/rknpu2-backend

**Comment by zhtroy** [comment]
I ran into the same problem when running rknn_matmul_demo, any further progress on this matter ? @marty1885

**Comment by marty1885** [comment]
@zhtroy Use RKNPU2 1.6.0. This repo is deprecated. They are now putting it under the [rknn-toolkit2](https://github.com/rockchip-linux/rknn-toolkit2/tree/master/rknpu2) project
